apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: rupesh7767/demo.jar:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 15
            failureThreshold: 10
            initialDelaySeconds: 50
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 15
            failureThreshold: 10
            initialDelaySeconds: 50
            timeoutSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  labels:
    app: app1
  annotations:
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 80
      targetPort: 80
